# Generated by Django 3.1.2 on 2020-10-18 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
        ('ferias', '0002_auto_20201018_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='aprovador',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ferias',
            name='solicitante',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='descricao',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='justificativa',
            field=models.CharField(max_length=480),
        ),
    ]
