# Generated by Django 3.0 on 2020-10-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painelInformacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painelinformacoes',
            name='dataCriacao',
            field=models.DateField(max_length=12),
        ),
    ]
