# Generated by Django 3.1.1 on 2020-10-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketstatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=140)),
                ('descricao', models.TextField()),
                ('dataCriacao', models.DateField(max_length=12)),
                ('dataFim', models.DateField(max_length=12)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketstatus.ticketstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
