# Generated by Django 3.1.2 on 2020-10-18 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketstatus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_aletracao', models.DateField(max_length=20)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketstatus.ticketstatus')),
                ('ticketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickets')),
                ('usuario_alteracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
