# Generated by Django 3.0 on 2020-10-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicoTicket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicoticket',
            old_name='ultima_aletracao',
            new_name='ultima_alteracao',
        ),
    ]
