# Generated by Django 3.1.1 on 2020-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_auto_20200916_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='intervaloFim',
            field=models.TimeField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='horarios',
            name='intervaloInicio',
            field=models.TimeField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='entrada',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='horario',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='saida',
            field=models.TimeField(max_length=20),
        ),
    ]
