# Generated by Django 3.1.1 on 2020-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_auto_20201016_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horario',
            field=models.CharField(max_length=60),
        ),
    ]
